// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://kubocyhvejzgsisihhrt.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Ym9jeWh2ZWp6Z3Npc2loaHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzc4ODMsImV4cCI6MjA2MTc1Mzg4M30.fuvRFzX9ju0rmcJ-ZiVKbGedL8-xPXEWxcPK5VShpiE';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
